version: '3.8'
services:
  frontend:
    restart: always
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    restart: always
    build: ./backend
    depends_on:
      - postgres  
    ports:
      - "${PORT}:5000"
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"